version: "3.8"
services:
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: astra_app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
